import { register } from 'node:module';
import { readdirSync,readFileSync } from 'node:fs';
import {createSqliteD1} from './sqlite-d1';
register('./cloudflare-env-loader.mjs',import.meta.url);
const {env}=await import('cloudflare:workers');
const database=createSqliteD1();
(env as unknown as {DB:unknown}).DB=database.d1;
for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort()) database.sqlite.exec(readFileSync(`drizzle/${name}`,'utf8'));
process.env.MORPH_AUTH_MODE='demo';
process.env.MORPH_ALLOW_RULE_BASED_PLANNER='true';
process.env.MORPH_APP_ORIGIN='http://localhost';
const {ensureAppActor}=await import('../../db/app-state');
await ensureAppActor(new Request('http://localhost/api/app-state'));
process.env.MORPH_APP_ORIGIN='https://morph.example';
process.env.MORPH_OIDC_ISSUER='https://id.example';
process.env.MORPH_OIDC_AUTHORIZATION_URL='https://id.example/authorize';
process.env.MORPH_OIDC_TOKEN_URL='https://id.example/token';
process.env.MORPH_OIDC_JWKS_URL='https://id.example/jwks';
process.env.MORPH_OIDC_CLIENT_ID='morph';
process.env.MORPH_OIDC_CLIENT_SECRET='test-only-not-a-real-secret';
